### ISSUE TITLE
JFXDecorator scales off the stage

### ISSUE THREAD

**Issue by bmoore27** [jfoenixadmin/JFoenix#1037]
I am encountering a scaling issue with JFXDecorator. If I try to scale the scene the controls on the right side of the decorator and the right side of the borderPane are always drawn off the stage. I can only see the controls if I resize the window to a much smaller width, but only a portion of the full screen icon.

To see this behavior, try using the demo application and adding the following two lines of code to `MainDemo.java` and add the import of `javafx.scene.transform.Scale` :

`Scale scale = new Scale(2, 2);`
`scene.getRoot().getTransforms().add(scale);`

Is there something I am missing when I attempt to scale the scene using `javafx.scene.transform.Scale`?

**Comment by jfoenixadmin** [comment]
Hello @bmoore27,
Well, JFXDecorator is also a Node and it's the scene root, so you are scaling the decorator itself instead of its content. You need to scale the content of the decorator instead of the decorator itself.

I tried it myself, and it seems there is a minor clipping issue that needs to be fixed when the content is scaled.

Thanks @bmoore27  for pointing out the issue 👍 
Regards,

**Comment by jfoenixadmin** [comment]
I pushed a fix for the minor clipping issue, it will be part of the next release. 
It works now, when the decorator content is scaled.

**Comment by bmoore27** [comment]
Thanks @jfoenixadmin for the update. I appreciate the quick attention. 

I intended to scale the decorator and the content. My goal is to define a few layouts for varying aspect ratios/display densities and then scale to fill in between.
