### ISSUE TITLE
import issue in new scenebuilder

### ISSUE THREAD

**Issue by mokun** [jfoenixadmin/JFoenix#112]
Hi, 

Awesome work on porting the material design into javaFX!

Your website setup said I can "Import JAR/FXML file" in scene builder

However, I downloaded gluon's updated scene-builder from [(http://gluonhq.com/labs/scene-builder/]

Version 8.2.0
Date: 2016-05-18

it won't let me import your jfoenix.jar

is there any simple way to make jfoenix work with the latest scene-builder ?

Thx much!

Manny

**Comment by jfoenixadmin** [comment]
this issue might be related to #105

**Comment by sluedecke** [comment]
It worked for me, but it did not make the JFXTreeTableColumn available as an object.  Tested with Scenebuilder 8.0.0 and 8.2.0 from gluonhq

**Comment by John-Weetaker** [comment]
it worked for me too no problem for import the jar

**Comment by jfoenixadmin** [comment]
Please note that not all JFoenix controls are scene builder compatible yet. thanks

**Comment by mokun** [comment]
> it worked for me too no problem to import the jar

But my question is how do you successfully import a jar? what are the exact steps taken ?

If I choose "File", 'Import", there are only two options, namely "FXML" and "Media".

It would open up a FileChooser and I have to type in "*" in the "File name:" textfield in order to highlight the jfoenix.jar file.

Obviously, "FXML" restricts files to *.fxml while "Media" restricts files to all kinds of audio/video format such as "jpg. png, mp3...." 

I've tried both of them and a yellow note popping up saying "Failed to import..."

.jar file is not supposed to be imported this way in scenebuilder.

am I missing something?

I tried the original Oracle version 2.0 scene builder with the same result.

**Comment by John-Weetaker** [comment]
![jfoenix issue](https://cloud.githubusercontent.com/assets/18209197/16281853/73758078-38c6-11e6-944b-c4beb5262363.JPG)
yes you miss something just click in the top, and right of the field for search library in scene builder see the attach file image

**Comment by mokun** [comment]
oh ic. thx!

**Comment by aminabs** [comment]
Hi,
I've faced two issues with the latest scene builder from gluon (x64 version) and jfoenix-1.0.0.
I already imported the jfoenix jar file.
I am using windows 8.1 Enterprise (64-bit operating system, x64 based processor)

**ISSUE 1:**
I add a border pane and put a JFXButton in the center area. It's OK. I can press ctrl+p to play with the preview; the button is clickable and the rippler effect shines.
I now save it an fxml file, close scenebuilder and double click on the fxml file.
It opens and I can't see the jfxbutton no more. There is a warning sign on the button's shortcut in the hierarchy view on the left hand side of scenebuilder. It tooltips "unresolved class jfxbutton", I am wondering how it is possible, since I can still see all JFX components on the library's custom components view of scenebuilder. More strange is when I drag the fxml file into a newly opened scenebuilder instance; guess what: the fxml content is shown correctly.

**ISSUE 2:**
I add a borderpane and a jfxtabpane in its center.
If I try to add a Tab into the tabpane, scenebuilder suspends (I did this process many times and it acts the same every time); it hangs and I have no way but to terminate its jvm process from windows task manager.

BTW,
another way of making scene builder know some custom component(s) is to put the custom jar file into this path:  %APPDATA%\Scene Builder\Library\

**Comment by aminabs** [comment]
Hi,
I've faced two issues with the latest scene builder from gluon (x64 version) and jfoenix-1.0.0.
I already imported the jfoenix jar file.
I am using windows 8.1 Enterprise (64-bit operating system, x64 based processor)

**ISSUE 1:**
I add a border pane and put a JFXButton in the center area. It's OK. I can press ctrl+p to play with the preview; the button is clickable and the rippler effect shines.
I now save it an fxml file, close scenebuilder and double click on the fxml file.
It opens and I can't see the jfxbutton no more. There is a warning sign on the button's shortcut in the hierarchy view on the left hand side of scenebuilder. It tooltips "unresolved class jfxbutton", I am wondering how it is possible, since I can still see all JFX components on the library's custom components view of scenebuilder.
If I drag a new jfxbutton and put it somewhere inside the design area, the unresolved issue is solved.
Finally, i I drag the fxml file into a newly opened scenebuilder instance; guess what: the fxml content is shown correctly.

**ISSUE 2:**
I add a borderpane and a jfxtabpane in its center.
If I try to add a Tab into the tabpane, scenebuilder suspends (I did this process many times and it acts the same every time); it hangs and I have no way but to terminate its jvm process from windows task manager.

BTW,
another way of making scene builder know some custom component(s) is to put the custom jar file into this path:  %APPDATA%\Scene Builder\Library\

**Comment by aminabs** [comment]
I've tried adding jfoenix jar file to classpath (setting app.classpath in file SceneBuilder.cfg), no help; Surprisingly, it worked right after setting the correct classpath; but it soon started to fail again when I changed the classpath to some wrong path, open the scenebuilder, then close it and set the classpath again to the correct path and open it again.

**Comment by aminabs** [comment]
I've opened an issue here: [asdfsdf](https://bitbucket.org/gluon-oss/scenebuilder/issues/91/custom-library-classpath-issue)

**Comment by JerJohn15** [comment]
@John-Weetaker Thank you so much!
