### ISSUE TITLE
How to change the icon date picker? Thanks

### ISSUE THREAD

**Issue by diegodesdecolombia** [jfoenixadmin/JFoenix#141]
![sin titulo](https://cloud.githubusercontent.com/assets/6775620/17956669/2e5d6b06-6a51-11e6-99fb-7b4c6df6b37e.png)

**Comment by jfoenixadmin** [comment]
This icon is SVGGlyph (JFoenix component), you can change it using the following css:

```
#arrow-button .jfx-svg-glyph{
	-fx-shape: "M512 854q124 0 211-88t87-212-87-211-211-87-211 87-87 211 87 212 211 88zM512 170q160 0 272 113t112 271-112 271-272 113-272-113-112-271 112-271 272-113zM534 342v224l170 100-32 52-202-120v-256h64zM336 144l-196 164-54-64 196-164zM938 244l-54 66-196-166 54-64z";
}
```
please note:

- **_-fx-shape_** property takes the svg path content as its input
- the previous css will change the icon everywhere in your application, you might want to add a css class selector before it e.g (_.my-date-picker #arrow-button .jfx-svg-glyph_) in order to specify the change for a certain control.

**Comment by gilad4** [comment]
Is there any way to change it using a png?
