### ISSUE TITLE
AnimatedThumb ignores CSS styling if slider is moved to extreme point

### ISSUE THREAD

**Issue by Gikkman** [jfoenixadmin/JFoenix#160]
If you change the `.jfx-slider .animated-thumb` to `-fx-background-color: transparent;`, then move the slider all the way to the left (using default left-right slider), the animated thumb becomes visible again. If you further move it out on the slider, it will still be visible.

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue :+1: . well the issue is that animated-thumb background color changes according to thumb background color, they are not separated for now. 

so if your goal is to hide the animated thumb then you can use the CSS property "visibility:hidden;"

however if your goal is to change the color of the slider then you need to change the thumb color instead of animated thumb

```
.jfx-slider .thumb{
   -fx-background-color:red;
}
```

**Comment by jfoenixadmin** [comment]
Hello,
a pseudo class has been added to animated thumb when setting the slider value to the minimum, you can do the following :
```
.jfx-slider .animated-thumb,
.jfx-slider .animated-thumb:min{
	-fx-background-color: transparent;
}
```
Regards,
