### ISSUE TITLE
JFXTextField Vanilla Border

### ISSUE THREAD

**Issue by ivanvinski** [jfoenixadmin/JFoenix#199]
# The Problem
When defining a `-fx-focus-color` property inside the CSS file, `JFXTextField` shows the _vanilla_ border (used in the default theme) along with changed focus color. However, when the focus color is changed using (Gluon) Scene Builder, only the focus color changes - it works as expected.

# CSS Code
```
* {
    accent-color: #FF5252;
}

.jfx-text-field {
    -fx-focus-color: accent-color;
}
```
# Image
The following image shows what happens after `-fx-focus-color` property is defined inside the CSS file.

![jfoenixbug](https://cloud.githubusercontent.com/assets/14854181/20427690/7b84869a-ad85-11e6-93eb-751765545d5e.png)

**Comment by jfoenixadmin** [comment]
Hello,
well the issue is due to default style class of TextField control. by default it sets the background color to white, when reapplying the css if it's not set (the focus border is part of the background). to overcome this issue, you need to set the background color in css manually to transparent or the desired color.

```
.jfx-text-field {
    -fx-focus-color: accent-color;
    -fx-background-color: TRANSPARENT;
}
```

Regards,

**Comment by ivanvinski** [comment]
That fixed the issue.

Just a small suggestion - there could be a note on the [Styling Properties of Input Fields](http://www.jfoenix.com/documentation.html#InputField) saying that.

Anyhow, thank you! :)

**Comment by jfoenixadmin** [comment]
hopefully the documentation will get updated soon, as it's a bit old and doesn't cover all JFoenix controls.

Regards,
