### ISSUE TITLE
Individual GUI components

### ISSUE THREAD

**Issue by sacOO7** [jfoenixadmin/JFoenix#209]
Hi ,
I was trying to develop desktop application for my new project. It needed Material Table in order to store entries in the form of rows and columns. I downloaded your project ,but it was too difficult to separate individual component from project. Are there any future plans to break down project into easy to use individual components ? I mean it will also make code more readable and will favour more contributions.

**Comment by jfoenixadmin** [comment]
Hello,
All that you need to do is to include JFoenix.jar in your project in order to use material design controls (JFXButton, JFXTextField,...) which are separate from each others. If you can provide a detailed example about your suggestion, it would be appreciated. Otherwise this issue will be closed as it's very vague and not clear.

Regards,
