### ISSUE TITLE
JFXDialog very slow/laggy transition animation

### ISSUE THREAD

**Issue by ralenmandao** [jfoenixadmin/JFoenix#213]
```
public class SampleApp extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        StackPane stackPane = new StackPane();
        stackPane.setStyle( "-fx-effect: dropshadow(three-pass-box, rgba(0,0,0,0.8), 10, 0, 0, 0);" );
        Button button = new Button( "Click Me" );
        button.setOnAction( e -> {
            JFXDialog dialog = new JFXDialog( stackPane, new Label("awe"), JFXDialog.DialogTransition.CENTER);
            dialog.show();
        } );
        stackPane.getChildren().add( button );
        Scene scene = new Scene( stackPane, 900, 700 );
        primaryStage.setScene( scene );
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch( args );
    }
}

```

When using dropshadow effect the transition of the dialog seems very laggy,
but without the dropshadow effect, it works fine. Im using mac book retina, also when my scene size is 500x500 it works fine.

**Comment by jfoenixadmin** [comment]
Hello, 

Thanks for pointing out the issue, we tested your code on a windows pc and it's working fine. The issue might be related to mac and retina display, we need to test that.

Generally speaking, effects in javafx reduces the animation performance dramatically so try to avoid them if possible.

Regards,

**Comment by gabrielpaim** [comment]
Is there any update on this? I'm also experiencing some issues with the slow animation. As @jfoenixadmin suggested, I'm also noticing that this issue is highly related to hardware GPU. However, I could also notice this behavior in PCs running Windows. As it seems, the bigger the screen (overlay), the slower the animation.

This may be related to https://github.com/jfoenixadmin/JFoenix/issues/537.

For now, I'm giving up on this JFXDialog. I'm currently on 8.0.3 version. Maybe in the future this animation becomes smoother for lesser hardwares :-)
