### ISSUE TITLE
JFXTableView MouseEvent does not work properly

### ISSUE THREAD

**Issue by Schlabberlachs** [jfoenixadmin/JFoenix#215]
If you click on a label in the Listview, the Eventhandler will not be executed properly.

import com.jfoenix.controls.JFXListView;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class ListViewTest extends Application{

    public static void main(String[] args){
        launch(args);
    }

    public void start(Stage stage){

        JFXListView jfxList = new JFXListView();
        ListView javaList = new ListView();

        for (int i = 0; i < 10; i++) {
            jfxList.getItems().add(new Label("Label " + i ));
            javaList.getItems().add(new Label("Label " + i));
        }

        jfxList.setOnMouseClicked(event ->  System.out.println(jfxList.getSelectionModel().getSelectedItem()));

        javaList.setOnMouseClicked(event -> System.out.println(javaList.getSelectionModel().getSelectedItem()));

        BorderPane borderPane = new BorderPane();
        borderPane.setRight(javaList);
        borderPane.setLeft(jfxList);

        Scene scene = new Scene(borderPane);
        stage.setScene(scene);
        stage.show();

    }
}

However the normal Fx ListView works fine.

**Comment by Schlabberlachs** [comment]
Thank you very much!

**Comment by eralpsahin** [comment]
I don't think that this fix is a correct one. After this change, datafx core gives error saying **"datafx Can't find an action with id popup"** (or any other label from the demo) since there is an annotation **@ActionTrigger** to each Label but there is no **@ActionMethod** annotation for them. 

I was tackling this problem, and I tried to add **@ActionMethod** to each label to control the flow, then the list started to react only to double clicks. I changed **SideMenuController**  to a previous commit and everything got back to normal.
