### ISSUE TITLE
JFXTextField Skin not working on mobile device

### ISSUE THREAD

**Issue by rjahn** [jfoenixadmin/JFoenix#24]
The JFXTextField has a different skin on mobile devices (with javafxports).

Desktop:

![desktop](https://cloud.githubusercontent.com/assets/1307043/11606939/4353db18-9b34-11e5-8dbc-66e5579db9ea.png)

compared to desktop:

![device](https://cloud.githubusercontent.com/assets/1307043/11606938/3a67d6f8-9b34-11e5-9eb7-a9908410ff0c.png)

**Comment by jfoenixadmin** [comment]
Well, it seems that javafxports is forcing Java textfieldSkin on android. i believe this issue should be directed to JavaFXPorts

**Comment by rjahn** [comment]
I didn't check what JavaFXPorts does, but created an issue: https://bitbucket.org/javafxports/android/issues/79/textfield-overrides-custom-skin

**Comment by jfoenixadmin** [comment]
we fixed this issue as we added custom JFXTextFieldSkin for android, Note that: NO changes need to be applied to your code.

however you need to use the android version of JFoenix, you can either rebuild the library or download it using the following link:

http://www.jfoenix.com/download/jfoenix-0.0.0-SNAPSHOT-retrolambda.jar

plz confirm if the problem is fixed, thanks.

**Comment by rjahn** [comment]
Your fix works. It would be better if JavaFXPorts solves such problems, but there was no response to the ticket... So thanks for your solution.
