### ISSUE TITLE
JFXDialog in BorderPane

### ISSUE THREAD

**Issue by marsteff** [jfoenixadmin/JFoenix#27]
Hello,

when i try using JFXDialog in a BorderPane, the the Dialog will open in space outside of the application, I can see only i tiny edge.

I can show an example if neccessary for recreate the problem.

**Comment by jfoenixadmin** [comment]
sure, plz send an example

**Comment by jfoenixadmin** [comment]
the issue is that we are adding the dialog to the parent using getChildren().add() however this doesn't work in case of BorderPane, so we need to implement a special case regarding the BorderPane.

to solve this issue temporary you can set the BorderPane inside a StackPane and set the dialog container to be the StackPane instead of the BorderPane.
