### ISSUE TITLE
JFXDatePicker inside JFXDialog bug

### ISSUE THREAD

**Issue by lucasfernog** [jfoenixadmin/JFoenix#360]
The label indicating the current month/year is not correctly positioned, overlapping the navigation arrows.

![bug](https://user-images.githubusercontent.com/20051258/27986189-22435ca6-63d2-11e7-8c47-88623b04dac3.png)

**Comment by lucasfernog** [comment]
JFXTimePicker inside JFXDialog is even worse :/

**Comment by jfoenixadmin** [comment]
Hello,
Please note that JFXDialogLayout applies style classes to heading, body and actions container.
in the main demo, we are applying the following css:
```
 .jfx-layout-body .label {
    -fx-font-size: 14.0px;
    -fx-pref-width: 400.0px;
    -fx-wrap-text: true;
}
```
this will update any label in JFXDialogLayout including date/time pickers. you can fix this by changing in `jfoenix-main-demo.css` and put `.jfx-layout-body > .label` instead of  `.jfx-layout-body .label`.

in case you were using jfoenix-main-demo.css in your application, it's advised to review the css file first as it's not written to be used as a template.

Regards,
