### ISSUE TITLE
JFXTreeTableView last column cropped

### ISSUE THREAD

**Issue by AhmedMouradDev** [jfoenixadmin/JFoenix#398]
I've a TreeTableView the columns of which are created dynamically according to what the user chooses from a CheckedListView, everything works out of the box except for the last column which is cropped out but the view's boundaries as seen below with 42 columns:

![image](https://user-images.githubusercontent.com/29189251/29224479-d3928c12-7eca-11e7-9bf9-06140534bb7b.png)

But the problem arises independently from how many columns there are, Just when there are enough columns to have a horizontal scrollbar if not it just works fine as seen below:

![image](https://user-images.githubusercontent.com/29189251/29224845-467dde06-7ecc-11e7-8004-8bccaf66ba90.png)

And also for that matter, is there a way to  stretch the columns to fill the view's width if their overall width is less than the view's width because when a row is selected with few columns it just looks weird

![image](https://user-images.githubusercontent.com/29189251/29225120-4bb23b0a-7ecd-11e7-9849-36c2fa95ba54.png)

Best Regards,

**Comment by jfoenixadmin** [comment]
Hello,
This issue is related to resize policy used in TreeTableView/TableView controls, here is an example to change the resize policy:

https://stackoverflow.com/questions/11484960/table-column-wont-take-full-size-of-the-table-view-in-javafx

will close this issue as it's not related to JFoenix.

Regards,
