### ISSUE TITLE
How can we edit containers without getting NullPointerException?

### ISSUE THREAD

**Issue by mayuso** [jfoenixadmin/JFoenix#416]
I am trying to populate a comboBox (Also set text to some labels, and a couple more things, but let's keep it simple in this example, let's focus on the comboBox, as every case basically has the same problem):

I have a comboBox declared in a FXML file, the FXML file loads well but I get NullPointerException when trying to edit the information of the ComboBox, this is what I have (Reduced, to keep it simple, the actual code adds a lot more cities):
    
    @FXML
    ComboBox myComboBox;

    @PostConstruct
    public void init() throws Exception {
        myComboBox.getItems().clear(); //Make sure it is clear
        myComboBox.getItems().add("Madrid");
    }

I get NullPointerException when trying to clear the information, if I delete the clear(), I also get NullPointerException when trying to add any element to the ComboBox, it feels like the ComboBox is still not loaded even though I set init() to @PostConstruct. 

What am I doing wrong here?

Thank you for your patience.

**Comment by jfoenixadmin** [comment]
Hello,
if you can provide the fxml for this controller, we might able to help. 

Regards,

**Comment by rfenters95** [comment]
@mayuso In your FXML file have you set the ComboBox's `fx:id` to `fx:id="myComboBox"`? If not this would cause a NullPointerException. As referencing FXML from Java requires the Java variable name to be the same as the `fx:id` of the desired FXML element, example `@FXML ComboBox myComboBox` needs `fx:id="myComboBox"`. Otherwise the compiler, throws a NullPointerException because the FXML is never injected during initialization therefore your ComboBox variable is null, yet your init method is still attempting to call its methods. 

<br>

**Example**

For the Java code you have provided

```java
@FXML
ComboBox myComboBox;

@PostConstruct
public void init() throws Exception {
    myComboBox.getItems().clear(); //Make sure it is clear
    myComboBox.getItems().add("Madrid");
}
```

Requires an FXML ComboBox element with `fx:id="myComboBox"`

```fxml
<ComboBox fx:id="myComboBox" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefWidth="150.0" />
```

**Comment by mayuso** [comment]
Thank you both for your answers. 

I just checked my whole code and realised I was trying to add text to my elements (ComboBox, Labels...) from another controller class which was trying to add new text before the elements were loaded. Newbie fails, I guess.

I am sorry. JFoenix is working fine, I am the one who is not.
