### ISSUE TITLE
JFXRippler and mouse transparency

### ISSUE THREAD

**Issue by LosTigeros** [jfoenixadmin/JFoenix#486]
Hello.
I've updated JFoenix to latest version.

Now i saw that rippler works in JFXListView when item in listview has `setMouseTransparent(true);`.
But when i want to use rippler separately then when I setted up a control which has `setMouseTransparent(true);` and rippler is transparent then its just not work.

Previously it worked just fine.

**Comment by jfoenixadmin** [comment]
Hello,
Previously the JFXRippler itself was responsible to trigger the ripples effects on mouse clicks.
It's been updated in the latest version, and set to be mouse transparent by default. 
Now The control is responsible to trigger the ripple effect on mouse clicks instead of the rippler itself (so if the control is set to be mouse transparent then it won't  trigger the ripple effect).

Regards

**Comment by LosTigeros** [comment]
Okay. Now I understand that behaviour. Thanks for fast response.
