### ISSUE TITLE
JFXTabPane won't animate added tabs

### ISSUE THREAD

**Issue by mordechaim** [jfoenixadmin/JFoenix#519]
As far as animation works on `JFXTabPane`, it doesn't track new added tabs after setting the items list.

This might be as easy as setting up list change listeners.

**Comment by mordechaim** [comment]
Also noticed that the selection line would not follow tab width if title is changed to a longer text while on focus. It will only change if I move away and come back.

**Comment by jfoenixadmin** [comment]
Hello,
Regarding the animation, it works when selecting a tab from the tab pane. In order to trigger the animation when adding a new tab you have to select it in code.

Regarding the selection line, you are right it needs to be refreshed when changing the tab layouts. thanks for pointing out the issue 👍

Regards,
