### ISSUE TITLE
Slow drawer animation on fullscreen

### ISSUE THREAD

**Issue by Djaler** [jfoenixadmin/JFoenix#537]
When the application window is enlarged, the animation speed slows down

**Comment by jfoenixadmin** [comment]
Hello,
can you provide a simple example demonstrating the issue? 
also please note that JavaFX animation can be affected by any other application using the GPU.

Regards,

**Comment by Djaler** [comment]
This affect me even in your demo. We reproduce it on many computers

**Comment by Djaler** [comment]
Also, it affects me if I open dialogs. Looks like there some performance issues in overlay rendering

**Comment by jfoenixadmin** [comment]
was not able to reproduce using the main demo.

you can try adding he following VM arguments when launching the JavaFX application
` -Dprism.order=es2,d3d,es1,sw`
to make sure JavaFX is using hardware acceleration.

**Comment by Djaler** [comment]
It used d3d

**Comment by jfoenixadmin** [comment]
does the animation play smoothly after?

**Comment by Djaler** [comment]
No. I mean, it used d3d with and without this arguments

**Comment by jfoenixadmin** [comment]
After some investigations, it seems that animating the overlay opacity is affecting the animation performance. However this effect seems to vary according to the drawer content somehow. 

I tried using `setCache/setCacheHint` methods however no luck in solving the issue.

**Comment by Djaler** [comment]
For example, Intel Core i3 6100U (2.3Ghz), DDR4 4096Mb

**Comment by Djaler** [comment]
Can I disable this overlay animation somehow?

**Comment by jfoenixadmin** [comment]
currently there is no public api to disable the overlay animation

**Comment by jfoenixadmin** [comment]
but in general for javafx animation to run smoothly you need a decent GPU, in order to use hardware acceleration.

**Comment by Djaler** [comment]
> currently there is no public api to disable the overlay animation
Maybe I can override something to get to this feature?

**Comment by jfoenixadmin** [comment]
you can't disable the animation as it's part of the animation timer. However you can extend JFXDrawer and replace the 1st child (which is the overlayPane) with your own overlay, and override the methods open/close to show/hide your custom overlay.

**Comment by stormtroop** [comment]
i noticed that the animation is pretty slow on our java-application too.,
i´m running a macbook pro (2,3 Ghz i7, 8GB RAM, Nvidia GT 650M with 2GB RAM)

![image](https://user-images.githubusercontent.com/15097024/34651172-e9a84baa-f3cc-11e7-9f0f-80fec52c8c36.png)

same on iMac (4Ghz i7, 32 GB RAM, Nvidia GTX 970 with 8GB RAM)

first-time opening time: 3,5 seconds
second, third time: 0,5-1 second

So like @jfoenixadmin mentioned, the issue is associated with the content. i gonna try out how much time it needs, without a menu

**Comment by jfoenixadmin** [comment]
Hi,
After some trials, I manged to improve the drawer performance by caching the actual content. 
Which means that using `setCache/setCacheHint` on the content pane will not affect the performance, instead you need to cache the actual nodes in the content (e.g if the content was a listview with a custom list cell, you need to cache the list cell itself in order to improve the animation performance)
Hope this info helps you to solve your issue.

Regards,

**Comment by gabrielpaim** [comment]
I'm also experiencing this problem with JFXDialog. 

As suggested by @Djaler, I also would like to disable the overlay animation.
Set 'cache' and 'cacheHint' (to SPEED) doesn't change the behavior.
Calling java with -Dprism.order=es2,d3d,es1,sw doesn't seem to make any relevant difference.

Well, I'll abandon this JFXDialog for now... Maybe in the future :-)

**Comment by jfoenixadmin** [comment]
@gabrielpaim , i just added a new boolean property `cacheContainer` to JFXDialog. setting this property to true will cache the parent content and hopefully fix the laggy animation

**Comment by gabrielpaim** [comment]
Ok, thank you. I'll check this out when I have some spare time.

**Comment by jfoenixadmin** [comment]
@Djaler I added a caching policy to JFXDrawer to improve animation performance. by default it's set to NONE, you can try using CACHE or IMAGE. It will be included in the next release. 

Regards,

**Comment by Djaler** [comment]
@jfoenixadmin that's cool, thanks
