### ISSUE TITLE
JFXDrawerStack setContent seems odd to me

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#60]
Hi,
JFXDrawerStack.setContent looks like this:

    public void setContent(Node content){
		this.content = content;
		if(drawers.size() > 0) drawers.get(0).setContent(content);
		else this.getChildren().add(this.content);
	}

I wonder why it is performing a call to setContent on the drawer whereas one is simply able to call setContent on any drawer if desired? 

To be honest, I can't understand the drawer.setContent behaviour; I do not see anything when calling the method, and I have to setSidePane on the drawer to see something inside the drawer when it opens.

**Comment by jfoenixadmin** [comment]
Hi, 

the drawer control has 2 main children, the content and the sidepane of the drawer. 
**content**  is the pane that will be shown behind the drawer.
**sidepane** is the pane that will be shown once the drawer is drawn from one of the sides.
<pre>
if(drawers.size() > 0) drawers.get(0).setContent(content);
</pre>

this is used to set the content to the top drawer in the stack, otherwise it won't work.
JFXDrawerStack is a stack of drawers on top of each others, the content node **MUST** be set to be the top drawer content each time a drawer is drawn.

**Note:** that drawing a drawer will make it at the top of the stack.

**Comment by aminabs** [comment]
Thank you.
So, my question should be like this:
Can I use JFXDrawer without using JFXDrawerStack? If yes, how can I toggle the drawer on its own since the toggleDrawer is a method of the stack class.
If no, why not? If the drawer can show a content and overlay a sidepane on it, it should be usable independent from JFXDrawerStack? Am I wrong?

**Comment by jfoenixadmin** [comment]
sure you can use JFXDrawer without the JFXDrawerStack. JFXDrawerStack is used when having multiple drawers on the same node thus toggling drawers must be controlled inside the drawers stack.

to toggle the drawer, use the methods draw() and hide() in JFXDrawer.

**Comment by aminabs** [comment]
Great thanks.
BTW,
Sometimes, the hide method does not completely hide the drawer and I believe its an issue (related to issue #64). However, I have found a workaround for that:
just set default size to zero when you hide the drawer, and do not forget to set it to your desired size before your show it again.
