### ISSUE TITLE
JFXComboBox validation

### ISSUE THREAD

**Issue by vigneshrcsengg** [jfoenixadmin/JFoenix#777]
How does the **JFXComboBox** validation works? I don't have the clear information on the internet through and in this repository also...

And it is not straightforward like **JFXTextField**

When I tried to use below code the **combo box dissappe**r and no exception also. The JFXCombobox in FXML file.
Question, how to validate it on change??

`ValidationFacade currencyFacade = new ValidationFacade();`
`currencyFacade.setControl(mCurrency);`
`currencyFacade.setValidators(new RequiredFieldValidator());`

Why simple validation on the complicated way... I am using version 8.0.5.

**Comment by jfoenixadmin** [comment]
Hello, Well validation facade is a wrapper node. So, it needs to be added to the scene instead of the combobox. ValidationFacade was created in order to make validation generic so it can be applied on any node on the scene. However I agree with you, JFXCombobox should have a straight forward validation similar to JFXTextField. Maybe will add this feature in later versions of JFoenix,
Meanwhile feel free to add your own contribution to JFoenix.

Regards,

**Comment by vigneshrcsengg** [comment]
Thanks for the update, when the 8.0.6 will be release??

**Comment by jfoenixadmin** [comment]
Hopefully next month

**Comment by vigneshrcsengg** [comment]
Any example for this validation JFXComboBox Validation?? I'm using the 8.0.7 version now...

**Comment by jfoenixadmin** [comment]
it's the same as JFXTextField

**Comment by vigneshrcsengg** [comment]
Any example code?

**Comment by jfoenixadmin** [comment]
`combo.getValidators().add(ValidatorBase)`
