### ISSUE TITLE
JFXScrollPane does not allow centering of nodes (specifically JFXMasonry)

### ISSUE THREAD

**Issue by SwissCheese5** [jfoenixadmin/JFoenix#898]
![2018-12-17_20-34-37](https://user-images.githubusercontent.com/7407478/50108121-192ab280-023d-11e9-8c39-52f7f3cdda3c.gif)

The masonry is not centered and cannot be centered, I applied

`			StackPane.setAlignment(masonry, Pos.TOP_CENTER);
`
and 

`			scrollpane.setAlignment(Pos.CENTER);
`
with no luck

**Comment by DropSnorz** [comment]
Hi @Demoniaque . I'm not sure that it's an issue with the `JFXMasonryPane`.

Without more information, i guess that the extra space on the right is generated by the masonry component. Placed in a `StackPane`, the component will grow to take all the available place. For each row, there is not enough space to add a new reddit block on the left, so the block is added to a new line. The masonry pane is probably centered but due to this extra space, childs are not centered on the scene. 
You can easily check that by adding custom background color to see which component is not centered.

```
masonry.setStyle("-fx-background-color: red);

stackpane.setStyle("-fx-background-color: blue);
```

You can try to define a pref and/or max size for your MasonryPane. You can also use a GridPane if you just need a static grid layout with fixed row and column size.

**Comment by Demoniaque** [comment]
@DropSnorz You are correct, the masonry is trailing space and wrapping to a new row, but that's not the issue. The as the window resizes, the panes should all shift to the center with it. If there is no space for a node on either left and right, then wrap the line.

![2018-12-18_08-50-32](https://user-images.githubusercontent.com/7407478/50136934-2f1e8e80-02a2-11e9-9479-46fd3f57c4e8.gif)

**Comment by DropSnorz** [comment]
As far as is know, there is not such feature for the masonry pane. The masonry pane will compute absolute childs coordinates, but childs positions will never be shifted to center the whole group of node if there is extra available space. I think you have to implement this behaviour.

**Comment by Demoniaque** [comment]
I don't have the most extensive knowledge of the system, but wrapping the panes in a borderPane and setting them in the center should do it... The borderpane should automatically adjust for the resizing.

**Comment by Demoniaque** [comment]
A clearer example with a low amount of cards: 
![image](https://user-images.githubusercontent.com/7407478/50766224-0e35d180-1281-11e9-95a6-2a293d0cd103.png)

They should all slide to the center.

**Comment by DropSnorz** [comment]
The MasonryPane itself is centered. For me, you can't center childs inside the MasonryPane beacause this feature seems not implemented. The first node will be always placed on the top-left corner by default.

![jfoenix-masonrypane-sketch](https://user-images.githubusercontent.com/15964929/50767070-cb252f80-127b-11e9-9115-25661ff8d692.png)

A tricky workarround could be to increase the left margin/padding based on the number of nodes loaded in the MasonryPane.

**Comment by Demoniaque** [comment]
Not even. I'm not sure where exactly, but somewhere in `layoutChildren` in JFXMasonryPane, there should be some math that adjusts/offsets the initial child location.

**Comment by jfoenixadmin** [comment]
@Demoniaque JFXMasonryPane doesn't support centering children by default. As @DropSnorz mentioned before, this feature is to be implemented.
Feel free to add your contribution to JFoenix.
Regards,

**Comment by rruffer** [comment]
does this feature already exist? Was solved?
