### ISSUE TITLE
Lag 

### ISSUE THREAD

**Issue by RobinMalfait** [jfoenixadmin/JFoenix#90]
Hello

I'm on a Macbook Pro retina, and my display is scaled so I have more room.
But when I resize the application to fit my whole screen, the application lags.

The rippler effects on buttons / tabs, and when changing tab it also lags.

Is this a known issue?
Do you want me to make a video to demonstrate it?

Thanks

**Comment by jfoenixadmin** [comment]
Hello, 
sure can you make a demonstration?

**Comment by RobinMalfait** [comment]
Due to recording everything is a bit slower, but you can see the difference:

video: http://d.pr/v/1dTKy

if not clear, I'll try to make a better video later this day :)

**Comment by RobinMalfait** [comment]
This might be a better video: http://d.pr/v/142OP

**Comment by jfoenixadmin** [comment]
Well, I can see your point. But not sure how to reproduce (will try), if you can provide a sample example it would be great. 

Regards,

**Comment by jfoenixadmin** [comment]
Hello, 
it seems there is an issue in JavaFX performance when increasing the size of the scene. maybe the high resolution of the Mac Pro is causing the lag.

Anyway, I did some updates regarding JFoenix optimization to improve performance, hope it helps in fixing the issue. you can download the latest version of JFoenix from the link:
http://www.jfoenix.com/download/jfoenix.jar

if the problem is not fixed, can you remove some nodes in your application in order to identify the node that is causing the issue?

Thanks,

**Comment by SaeedMasoumi** [comment]
Same issue, 
I think the problem is JFoenix. I have a 4k screen and test your demo and also [gluon-samples](https://bitbucket.org/gluon-oss/samples) which based on material design.
The drawer lags in your demo but it's ok in gluon. I tried to scale down my resolution to 1080 and now there's no lag anymore.

**Comment by jfoenixadmin** [comment]
can you upload a video testing JFoenix on 4K screen?
so we can identify if the lag is related to the drawer only or other controls.

Thanks,

**Comment by jfoenixadmin** [comment]
Hello, 
It seems the issue is related to javafx poor animation performance when having some effects (DropShadow) on the animated node.

http://stackoverflow.com/questions/14467719/what-is-the-best-way-to-display-millions-of-images-in-java

I removed the effect from the drawer side pane, and cached the tabpane node before animating it. the performance of your application, and JFoenix demo should be better when tested on 4K screen.

you can download the latest JFoenix jar using the following link:
http://www.jfoenix.com/download/jfoenix.jar

Regards,
