### ISSUE TITLE
how to change autocomplete popup bording color ?

### ISSUE THREAD

**Issue by Ligandfas** [jfoenixadmin/JFoenix#917]
Hi,
I am trying to change the autocomplete popup color from blue to another color and can't figure out how to do it.
![capture](https://user-images.githubusercontent.com/18163788/51072108-96d6b800-165b-11e9-9794-5359a465a1a2.jpg)

thanks

**Comment by schlegel11** [comment]
Hi,
yep it's a little hard to find because the popup is more or less represented by a `ListView`.
So you have to override the border color of the `ListView` in a CSS file.

So first you have to create a CSS file e.g. in your "resources" folder.
I have created a "main-app.css" file in the root of the "resources" dir.
Now you must set the CSS file to your `Scene` like:

```java
...
    Scene scene = new Scene(root, 300, 275);
    //Add the CSS  file.
    scene.getStylesheets().add(Main.class.getResource("/main-app.css").toExternalForm());
    primaryStage.setScene(scene);
    primaryStage.show();
...
```

In the CSS file you have to override the border color like:

```css
...
.jfx-autocomplete-popup .list-view {
    -fx-border-color: greenyellow;
}
...
```
And that's it :wink: 

![peek 2019-01-12 23-30](https://user-images.githubusercontent.com/5841076/51079138-39c21d00-16c2-11e9-9fc7-43ba52092474.gif)

Greetings

**Comment by Ligandfas** [comment]
Oh thank you it works , there is stil a blue color merged with the border one. I corrected it by using 
jfx-autocomplete-popup .list-view {
         -fx-border-color: #2e704a ;
         -fx-background-color: white;
         }
