### ISSUE TITLE
Change position of error-label.

### ISSUE THREAD

**Issue by SkaaRJik** [jfoenixadmin/JFoenix#924]
Hello. Using jfoenix 8.0.8. Is there any way to put error-label inside its text field? 
![default](https://user-images.githubusercontent.com/20535237/51449454-11dc5480-1d67-11e9-93ff-c925b94fd252.png)

**Comment by schlegel11** [comment]
Hi,
this is a little bit difficult but possible.
Unfortunately there is no CSS class for the ValidationPane or errorContainer in JFXTextField (I didn't found one maybe there is one :wink: ).
Only for the ValidationPane "error-label-container", "error-label" which doesn't help if we want to change the entire position.

So I wrote a method which access directly the Skin childs. 
Be careful with it because it can fail in the future with other jfoenix versions if the related Skin class childs will change.

```java
  private <T extends TextField & IFXLabelFloatControl> void validationPaneFormatter(
      T jfxTextField) {
    jfxTextField
        .skinProperty()
        .addListener(
            (observable, oldValue, newValue) -> {
              JFXTextFieldSkin textFieldSkin = ((JFXTextFieldSkin) newValue);
              ObservableList childs = textFieldSkin.getChildren();
              // Get validation pane.
              // It's always the last child. Be careful no get per type checking -> index can change
              // -> code will fail.
              ValidationPane validationPane = (ValidationPane) childs.get(childs.size() - 1);
              validationPane.setTranslateY(-24);

              // Set validation label to the right.
              // Again node is always first child but code can fail in future.
              StackPane labelStackPane = (StackPane) validationPane.getChildren().get(0);
              labelStackPane.setAlignment(Pos.TOP_RIGHT);
            });
    // Validate also directly on typing or better text change for not override the error label.
    jfxTextField
        .textProperty()
        .addListener((observable, oldValue, newValue) -> jfxTextField.validate());
  }
```

Use it like:

```java
...
    JFXTextField validationField = new JFXTextField();
    validationPaneFormatter(validationField);
...
```

Tested with JFXTextField demo:
Before:

![before](https://user-images.githubusercontent.com/5841076/51464596-3a178380-1d66-11e9-909b-d509363f35db.gif)

After:

![after](https://user-images.githubusercontent.com/5841076/51464611-426fbe80-1d66-11e9-89d7-01e6a057fc21.gif)

Greetings

**Comment by SkaaRJik** [comment]
> ValidationPane validationPane = (ValidationPane) childs.get(childs.size() - 1); validationPane.setTranslateY(-24);

This part works fine, my error-label moves up and it's great.

> StackPane labelStackPane = (StackPane) validationPane.getChildren().get(0); labelStackPane.setAlignment(Pos.TOP_RIGHT);

But there is a problem. It seems to me error-label or labelStackPane don't fill the parrent and error-text is on the left side.

![default](https://user-images.githubusercontent.com/20535237/51477884-b640b400-1dc4-11e9-9aed-27e84e57508f.png)

Of course, i can set pref, min and max size of error-label inside the CSS, but i believe it's the wrong way

**Comment by schlegel11** [comment]
Hi,
yep I'm sorry and it's also funny :smile:
Because the code was broken for the current jfoenix version and I commented like "..can be broken in future":wink: 

So the reason is that I'm working on the current master and didn't notice that there was a code change 10 days before. But this change is not in the current release version.

Here is the correct method which should work with the current release and also the new code version ... so currently :smile: 

```java
  private <T extends TextField & IFXLabelFloatControl> void validationPaneFormatter(
      T jfxTextField) {
    jfxTextField
        .skinProperty()
        .addListener(
            (observable, oldValue, newValue) -> {
              JFXTextFieldSkin textFieldSkin = ((JFXTextFieldSkin) newValue);
              ObservableList childs = textFieldSkin.getChildren();
              // Get validation pane.
              // It's always the last child. Be careful no get per type checking -> index can change
              // -> code will fail.
              ValidationPane validationPane = (ValidationPane) childs.get(childs.size() - 1);
              validationPane.setTranslateY(-24);

              // Set validation label to the right.
              // Again node is always first child but code can fail in future.
              StackPane labelStackPane = (StackPane) validationPane.getChildren().get(0);
              Label innerErrorLabel = (Label) labelStackPane.getChildren().get(0);
              StackPane.setAlignment(innerErrorLabel, Pos.TOP_RIGHT);
            });
    // Validate also directly on typing or better text change for not override the error label.
    jfxTextField
        .textProperty()
        .addListener((observable, oldValue, newValue) -> jfxTextField.validate());
  }
```

Greetings

**Comment by schlegel11** [comment]
So does it work like you want?

Greetings
