### ISSUE TITLE
jfoenix titledpane

### ISSUE THREAD

**Issue by jesa29** [jfoenixadmin/JFoenix#956]
Hi! I found nothing in google:
is there any .css for styling titledpane 'like material design' ? or need to do it manually
thanks

**Comment by jfoenixadmin** [comment]
Hi @jesa29 
Currently you have to do it manually, feel free to add your own contribution to JFoenix.

Regards,

**Comment by Linkadi98** [comment]
Hi @jesa29,
Well I have some stuffs for you to try with Google's Material on TitledPane.
When Google presented Material, it seems like all components are flat. So, my suggestion here is making titledpane flat, too.

`.titled-pane > .title {
    -fx-background-color: transparent;
    -fx-pref-height: 0.000001; // I make this small double number because I dont want to use the title of titledpane

}

.titled-pane > .title > .arrow-button .arrow{
    -fx-background-color: transparent;
    -fx-border-color: transparent;
    -fx-padding: 0 0 0 -10; // this is little tricky when you want to hide the arrow and do not know how to hide this arrow
}

.titled-pane > .content
{
    -fx-background-color: transparent;
    -fx-padding: 0 -1 -1 -1 ; // this padding setting will help you to ignore the U border when you try to set the background color for the content of titledpane. if you don't do this, because the default css of titledpane, it will appear the U border like I said before. 
    -fx-background-insets: 0 0 0 0; // well you can add this line or not, depending on you
}`

My css is very short because I just use titledpane a little bit to make sub menu. You can use this, I am confident to say that I make material titledpane. 
Thank!
