### ISSUE TITLE
Hello, is there any way to decrease the width of the selected line under the first tab?

### ISSUE THREAD

**Issue by mohamedG09** [jfoenixadmin/JFoenix#971]
![image](https://user-images.githubusercontent.com/40148715/55399306-d1196c80-555b-11e9-9f81-b2627bcc483f.png)

**Comment by jfoenixadmin** [comment]
It shouldn't be this long, @mohamedG09 can you provide a SSCCE demonstrating the issue?

**Comment by mohamedG09** [comment]
Sir, https://github.com/jfoenixadmin/JFoenix/issues/728
This is the same problem that I'm having, when I set the windows dpi to 100% everything worked just fine

**Comment by Linkadi98** [comment]
Hi @mohamedG09,
This bug's about HiDPI. It seems like no one can solve this problem when we change the scale to 125%, even admin :). Hope some one will be able to solve this in future :)

**Comment by jfoenixadmin** [comment]
if I was able to reproduce I would try to solve it. @Linkadi98 It seems you were able to reproduce, so can you give it a shot and identify the cause of this issue ?

**Comment by Linkadi98** [comment]
Well I tried in many ways including css but it was not solved. It seems like the line below the selected tab is not computed right when the scale is bigger than 100%, I think this problem comes from some functions (I don't know exactly which functions) when they compute the width of this line and render it to the scene, because the functions just compute right at 100% scale and wrong at others scales. @jfoenixadmin you guys should check this. I was stuck in this prob and my solution was ignoring the line (I made it transparent) and I used another way to tell that I select this tab. @mohamedG09 you can set text in the tab to another color instead of use this line when selecting tab which you want :)

**Comment by mohamedG09** [comment]
@Linkadi98 this will also do :D
